[IMP] optimised css
krman009/Daily-Task pull request #31
Opened 2019-10-15 11:04 UTC by sapanz

2019-10-16 16:36 UTC, krman009 requested changes
Please do the changes and indent the changed file using `space` instead of the current one which is `tab`.
Thanks for your work @sapanz :)

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	-moz-border-radius: 0.3em;
Remove lines: 21, 22.

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	-moz-border-radius: 0.3em;
Remove lines: 30, 31.

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	-o-transition: 0.1s all ease-in;
Remove lines: 40, 41.

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	/*background: #34495e;*/
Remove this comment line.

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	-moz-border-radius: 0.3em;
Remove lines: 61, 62.

2019-10-16 16:36 UTC, krman009 commented on styles/style.css
> +	/*margin: 0.2em;*/
Remove lines containing comment: 84, 85.

2019-10-19 13:07 UTC, sapanz commented
Changes done @krman009

2019-10-22 03:38 UTC, krman009 approved these changes
Thank you @sapanz :+1:

2019-10-22 03:45 UTC, merged